"""Название миграци

Revision ID: 1376fb5bf93d
Revises: ee5e8d424ea4
Create Date: 2025-01-27 22:19:07.875514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1376fb5bf93d'
down_revision = 'ee5e8d424ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
