"""Название миграци.

Revision ID: 3705d00991ac
Revises: 1376fb5bf93d
Create Date: 2025-01-28 10:55:42.946616
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3705d00991ac'
down_revision = '1376fb5bf93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_amount', sa.Integer(), nullable=False),
    sa.Column('invested_amount', sa.Integer(), nullable=False),
    sa.Column('fully_invested', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charity_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('charityproject')
    op.drop_column('donation', 'fully_invested')
    op.drop_column('donation', 'create_date')
    op.drop_column('donation', 'invested_amount')
    op.drop_column('donation', 'id')
    op.drop_column('donation', 'full_amount')
    op.drop_column('donation', 'close_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation', sa.Column('close_date', sa.DATETIME(), nullable=True))
    op.add_column('donation', sa.Column('full_amount', sa.INTEGER(), nullable=False))
    op.add_column('donation', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('donation', sa.Column('invested_amount', sa.INTEGER(), nullable=False))
    op.add_column('donation', sa.Column('create_date', sa.DATETIME(), nullable=False))
    op.add_column('donation', sa.Column('fully_invested', sa.BOOLEAN(), nullable=False))
    op.create_table('charityproject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_amount', sa.INTEGER(), nullable=False),
    sa.Column('invested_amount', sa.INTEGER(), nullable=False),
    sa.Column('fully_invested', sa.BOOLEAN(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('close_date', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('charity_project')
    op.drop_table('investment')
    # ### end Alembic commands ###