"""Название миграци

Revision ID: 51355ae4be6d
Revises: 1376fb5bf93d
Create Date: 2025-01-28 19:29:44.478018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51355ae4be6d'
down_revision = '1376fb5bf93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
