"""Название миграци

Revision ID: 8efbcdf5b54b
Revises: 0d8e28a04c9a
Create Date: 2025-01-26 15:40:55.886245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efbcdf5b54b'
down_revision = '0d8e28a04c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
